/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "confid-center_alarm-config": () => import("@/views/confid-center/alarm-config/index.vue"),
  "confid-center_organization-config": () => import("@/views/confid-center/organization-config/index.vue"),
  "confid-center_system-announce": () => import("@/views/confid-center/system-announce/index.vue"),
  "confid-center_system-config": () => import("@/views/confid-center/system-config/index.vue"),
  "data-center_alarm-record": () => import("@/views/data-center/alarm-record/index.vue"),
  "data-center_detection-record": () => import("@/views/data-center/detection-record/index.vue"),
  "data-center_equipment-info": () => import("@/views/data-center/equipment-info/index.vue"),
  "equipment-center": () => import("@/views/equipment-center/index.vue"),
  "monitor-center": () => import("@/views/monitor-center/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
  workbench: () => import("@/views/workbench/index.vue"),
  "workorder-center": () => import("@/views/workorder-center/index.vue"),
};
